# action.yml
name: 'HuaweiCloud PyPI CloudArtifact'
description: 'Action for uploading/downloading PyPI packages to HuaweiCloud PyPI CloudArtifact'
inputs:
  pypi-operation-type:
    description: 'install or upload. install: to install PyPI package from the repository; upload: publish PyPI package to the repository'
    required: true
    default: 'install'
  repository:
    description: 'The URL of the PyPI repository.'
    required: false
    default: 'https://pypi.org/simple'
  username:
    description: 'The registered username on the repository.'
    required: false
  password:
    description: 'The password that will used to authenticate the username.'
    required: false
  distutils-index-server:
    description: 'The name of the section describing a repository.'
    required: false
    default: 'pypi'
branding:
  icon: 'cloud'
  color: 'red'
runs:
  using: 'node16'
  main: 'dist/index.js'

